/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class Pagina extends javax.swing.JFrame {

    /**
     * Creates new form Pagina
     */
    public Pagina() {
        initComponents();
        this.setLocationRelativeTo(this);
        ingresarUsuarios();
        menu.setPreferredSize(new Dimension(50, menu.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        texto = new javax.swing.JLabel();
        cerrar = new javax.swing.JToggleButton();
        menu = new javax.swing.JPanel();
        ubicacionIconos = new javax.swing.JPanel();
        opcionMenu = new javax.swing.JButton();
        ubicacionOpciones = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        opcionUsuarios = new javax.swing.JLabel();
        panelCalculadora = new javax.swing.JPanel();
        opcionCalculadora = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JPanel();
        opcionHistorial = new javax.swing.JLabel();
        panelPlanilla = new javax.swing.JPanel();
        opcionPlanilla = new javax.swing.JLabel();
        OpcionesMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(96, 150, 186));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header.setPreferredSize(new java.awt.Dimension(750, 100));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pararMovimiento(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empezarMovimiento(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(39, 76, 119));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Calculadora Salarial.png"))); // NOI18N

        cerrar.setBackground(new java.awt.Color(96, 150, 186));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cerrar.png"))); // NOI18N
        cerrar.setBorder(null);
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cerrarHover.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrar(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 617, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(texto))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cerrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.setPreferredSize(new java.awt.Dimension(250, 450));
        menu.setLayout(new java.awt.BorderLayout());

        ubicacionIconos.setBackground(new java.awt.Color(163, 206, 241));
        ubicacionIconos.setMinimumSize(new java.awt.Dimension(50, 100));
        ubicacionIconos.setPreferredSize(new java.awt.Dimension(50, 450));
        ubicacionIconos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcionMenu.setBackground(new java.awt.Color(163, 206, 241));
        opcionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        opcionMenu.setBorder(null);
        opcionMenu.setBorderPainted(false);
        opcionMenu.setContentAreaFilled(false);
        opcionMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menuHover.png"))); // NOI18N
        opcionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPresionado(evt);
            }
        });
        ubicacionIconos.add(opcionMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 80));

        menu.add(ubicacionIconos, java.awt.BorderLayout.LINE_START);

        ubicacionOpciones.setBackground(new java.awt.Color(96, 150, 186));

        panelUsuario.setBackground(new java.awt.Color(39, 76, 119));
        panelUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuUsuarios(evt);
            }
        });

        opcionUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        opcionUsuarios.setForeground(new java.awt.Color(231, 236, 239));
        opcionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/usuario.png"))); // NOI18N
        opcionUsuarios.setText("Usuarios");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCalculadora.setBackground(new java.awt.Color(96, 150, 186));
        panelCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCalculadora(evt);
            }
        });

        opcionCalculadora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        opcionCalculadora.setForeground(new java.awt.Color(231, 236, 239));
        opcionCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/calculadora.png"))); // NOI18N
        opcionCalculadora.setText("Calculadora");

        javax.swing.GroupLayout panelCalculadoraLayout = new javax.swing.GroupLayout(panelCalculadora);
        panelCalculadora.setLayout(panelCalculadoraLayout);
        panelCalculadoraLayout.setHorizontalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalculadoraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(opcionCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCalculadoraLayout.setVerticalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionCalculadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelHistorial.setBackground(new java.awt.Color(96, 150, 186));
        panelHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuHistorial(evt);
            }
        });

        opcionHistorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        opcionHistorial.setForeground(new java.awt.Color(231, 236, 239));
        opcionHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/historial.png"))); // NOI18N
        opcionHistorial.setText("Historial");

        javax.swing.GroupLayout panelHistorialLayout = new javax.swing.GroupLayout(panelHistorial);
        panelHistorial.setLayout(panelHistorialLayout);
        panelHistorialLayout.setHorizontalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(opcionHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelHistorialLayout.setVerticalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialLayout.createSequentialGroup()
                .addComponent(opcionHistorial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPlanilla.setBackground(new java.awt.Color(96, 150, 186));
        panelPlanilla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oPlanillaClick(evt);
            }
        });

        opcionPlanilla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        opcionPlanilla.setForeground(new java.awt.Color(231, 236, 239));
        opcionPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panillas 1.png"))); // NOI18N
        opcionPlanilla.setText("Planilla");

        javax.swing.GroupLayout panelPlanillaLayout = new javax.swing.GroupLayout(panelPlanilla);
        panelPlanilla.setLayout(panelPlanillaLayout);
        panelPlanillaLayout.setHorizontalGroup(
            panelPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlanillaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPlanillaLayout.setVerticalGroup(
            panelPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanillaLayout.createSequentialGroup()
                .addComponent(opcionPlanilla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ubicacionOpcionesLayout = new javax.swing.GroupLayout(ubicacionOpciones);
        ubicacionOpciones.setLayout(ubicacionOpcionesLayout);
        ubicacionOpcionesLayout.setHorizontalGroup(
            ubicacionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubicacionOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPlanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ubicacionOpcionesLayout.setVerticalGroup(
            ubicacionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubicacionOpcionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panelCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(panelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(panelPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.add(ubicacionOpciones, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        OpcionesMenu.setBackground(new java.awt.Color(231, 236, 239));
        OpcionesMenu.setMaximumSize(new java.awt.Dimension(800, 434));
        OpcionesMenu.setMinimumSize(new java.awt.Dimension(800, 434));
        OpcionesMenu.setPreferredSize(new java.awt.Dimension(800, 434));

        javax.swing.GroupLayout OpcionesMenuLayout = new javax.swing.GroupLayout(OpcionesMenu);
        OpcionesMenu.setLayout(OpcionesMenuLayout);
        OpcionesMenuLayout.setHorizontalGroup(
            OpcionesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        OpcionesMenuLayout.setVerticalGroup(
            OpcionesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        getContentPane().add(OpcionesMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar

        System.exit(0);
    }//GEN-LAST:event_cerrar

    private void menuPresionado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPresionado

        if(presionado==false){
           opcionMenu.setIcon(iconoMenu);
           opcionMenu.setRolloverIcon(iconoMenuHover);
           esconderMenu(presionado);
           presionado=true;
       }
        else if(presionado){
           opcionMenu.setIcon(iconoFlecha);
           opcionMenu.setRolloverIcon(iconoFlechaHover);
           esconderMenu(presionado);      
           presionado=false;           
        }
        
    }//GEN-LAST:event_menuPresionado

    private void menuUsuarios(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuarios
        panelUsuario.setBackground(azulOscuro);
        panelCalculadora.setBackground(azulClaro);
        panelHistorial.setBackground(azulClaro);
        panelPlanilla.setBackground(azulClaro);
        ingresarUsuarios();
    }//GEN-LAST:event_menuUsuarios

    private void menuCalculadora(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCalculadora
        panelUsuario.setBackground(azulClaro);
        panelCalculadora.setBackground(azulOscuro);
        panelHistorial.setBackground(azulClaro);
        panelPlanilla.setBackground(azulClaro);
        calculadora();
    }//GEN-LAST:event_menuCalculadora

    private void menuHistorial(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistorial
        panelUsuario.setBackground(azulClaro);
        panelCalculadora.setBackground(azulClaro);
        panelHistorial.setBackground(azulOscuro);
        panelPlanilla.setBackground(azulClaro);
        historial();

    }//GEN-LAST:event_menuHistorial

    private void empezarMovimiento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarMovimiento

        xMouse=evt.getX();
        yMouse=evt.getY();       
    }//GEN-LAST:event_empezarMovimiento

    private void pararMovimiento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pararMovimiento
       int y =evt.getYOnScreen();
       int x= evt.getXOnScreen();
       setLocation(x-xMouse,y- yMouse );
    }//GEN-LAST:event_pararMovimiento

    private void oPlanillaClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oPlanillaClick
        panelUsuario.setBackground(azulClaro);
        panelCalculadora.setBackground(azulClaro);
        panelHistorial.setBackground(azulClaro);
        panelPlanilla.setBackground(azulOscuro);
        planilla();
    }//GEN-LAST:event_oPlanillaClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina().setVisible(true);
            }
        });
    }
    /***********************************************************************************/
    // metodos 
    // ESCONDE MUEVE EL MENU
        public void esconderMenu(boolean band){
        if(band==false){
            menu.setPreferredSize(new Dimension(50, menu.getHeight()));
            SwingUtilities.updateComponentTreeUI(this);
        }
        else{
                    menu.setPreferredSize(new Dimension(250, menu.getHeight()));
                    SwingUtilities.updateComponentTreeUI(this);
            }
    }  
        // MUESTRA LOS USUARIOS
        public void ingresarUsuarios(){
        opUsuarios.setSize(OpcionesMenu.getWidth(), OpcionesMenu.getHeight());
        opUsuarios.setLocation(0, 0);
        OpcionesMenu.removeAll();
        OpcionesMenu.add(opUsuarios);
        OpcionesMenu.revalidate();
        OpcionesMenu.repaint();

        }
        //MUESTRA LA CALCULADORA
         public void calculadora(){
        opCalculadora.setSize(OpcionesMenu.getWidth(), OpcionesMenu.getHeight());
        opCalculadora.setLocation(0, 0);
        OpcionesMenu.removeAll();
        OpcionesMenu.add(opCalculadora);
        OpcionesMenu.revalidate();
        OpcionesMenu.repaint();

        }
         //MUESTRA EL HISTORIAL
         public void historial(){
        opHistorial=new Historial();
        opHistorial.setSize(OpcionesMenu.getWidth(), OpcionesMenu.getHeight());
        opHistorial.setLocation(0, 0);
        OpcionesMenu.removeAll();
        OpcionesMenu.add(opHistorial);
        OpcionesMenu.revalidate();
        OpcionesMenu.repaint();

        }
         
        //MUESTRA LA PLANILLA
         public void planilla(){
        oPlanilla=new Planilla();
        oPlanilla.setSize(OpcionesMenu.getWidth(), OpcionesMenu.getHeight());
        oPlanilla.setLocation(0, 0);
        OpcionesMenu.removeAll();
        OpcionesMenu.add(oPlanilla);
        OpcionesMenu.revalidate();
        OpcionesMenu.repaint();

        }

    // atributos
    private int xMouse,yMouse;
    private Color azulOscuro=new Color(39,76,119);
    private Color azulClaro=new Color(96,150,186);
    private ImageIcon iconoMenu = new ImageIcon("src/assets/menu.png");
    private ImageIcon iconoMenuHover = new ImageIcon("src/assets/menuHover.png");
    private ImageIcon iconoFlecha = new ImageIcon("src/assets/flecha.png");
    private ImageIcon iconoFlechaHover = new ImageIcon("src/assets/flechaHover.png");
    private boolean presionado=true;
    private Usuario opUsuarios = new Usuario();
    private Calculadora opCalculadora=new Calculadora();
    private Historial opHistorial;
    private Planilla oPlanilla=new Planilla();
    cEmpleado empleados;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OpcionesMenu;
    private javax.swing.JToggleButton cerrar;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel opcionCalculadora;
    private javax.swing.JLabel opcionHistorial;
    private javax.swing.JButton opcionMenu;
    private javax.swing.JLabel opcionPlanilla;
    private javax.swing.JLabel opcionUsuarios;
    private javax.swing.JPanel panelCalculadora;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelPlanilla;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JLabel texto;
    private javax.swing.JPanel ubicacionIconos;
    private javax.swing.JPanel ubicacionOpciones;
    // End of variables declaration//GEN-END:variables
}
