
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atenea
 */
public class Planilla extends javax.swing.JPanel {

    /**
     * Creates new form planilla
     */
    public Planilla() {
        initComponents();
        modeloPlanilla = new DefaultTableModel();
        modeloPlanilla.addColumn("Id");
        modeloPlanilla.addColumn("Planilla");
        modeloPlanilla.addColumn("Mes");
        modeloPlanilla.addColumn("Año");
        modeloPlanilla.addColumn("Salario Neto");

        tablaPlanilla.setModel(modeloPlanilla);
        actualizarTablaPlanilla(planillasImpresas);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlanilla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        generarReporte1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        opcionPlanilla = new javax.swing.JComboBox<>();
        generarReporte2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 236, 239));
        setMaximumSize(new java.awt.Dimension(750, 461));
        setMinimumSize(new java.awt.Dimension(750, 461));

        tablaPlanilla.setBackground(new java.awt.Color(231, 236, 239));
        tablaPlanilla.setForeground(new java.awt.Color(39, 76, 119));
        tablaPlanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaPlanilla.setEnabled(false);
        tablaPlanilla.setGridColor(new java.awt.Color(39, 76, 119));
        tablaPlanilla.setShowGrid(true);
        jScrollPane1.setViewportView(tablaPlanilla);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 76, 119));
        jLabel2.setText("ID:");

        id.setForeground(new java.awt.Color(139, 140, 137));
        id.setText("ID localizar la planilla de un empleado en especifico");
        id.setMaximumSize(new java.awt.Dimension(285, 25));
        id.setMinimumSize(new java.awt.Dimension(285, 25));
        id.setPreferredSize(new java.awt.Dimension(285, 25));
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                introducirId(evt);
            }
        });

        generarReporte1.setBackground(new java.awt.Color(39, 76, 119));
        generarReporte1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        generarReporte1.setForeground(new java.awt.Color(231, 236, 239));
        generarReporte1.setText("Generar Reporte");
        generarReporte1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generarReporte1.setBorderPainted(false);
        generarReporte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reporte1(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 76, 119));
        jLabel5.setText("planilla:");

        opcionPlanilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "planilla 1", "planilla 2" }));

        generarReporte2.setBackground(new java.awt.Color(39, 76, 119));
        generarReporte2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        generarReporte2.setForeground(new java.awt.Color(231, 236, 239));
        generarReporte2.setText("Generar Reporte");
        generarReporte2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generarReporte2.setBorderPainted(false);
        generarReporte2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reporte2(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 76, 119));
        jLabel7.setText("Reporte 1");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 76, 119));
        jLabel8.setText("Reporte 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generarReporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generarReporte2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(opcionPlanilla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarReporte1)
                    .addComponent(generarReporte2))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reporte1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporte1
        texto = "";
        verificarEntero(this.id.getText());
        reporte = new Reporte(texto);
        reporte.setLocationRelativeTo(reporte);
        reporte.setVisible(true);


    }//GEN-LAST:event_reporte1

    private void reporte2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporte2

        texto = "";
        String planilla = opcionPlanilla.getSelectedItem().toString();
        reportePlanilla(planilla);
        reporte = new Reporte(texto);
        reporte.setLocationRelativeTo(reporte);
        reporte.setVisible(true);


    }//GEN-LAST:event_reporte2

    private void introducirId(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_introducirId
        this.id.setText("");
        this.id.setForeground(azulOscuro);
    }//GEN-LAST:event_introducirId
    
/**************************************************************************************************/
// ACTUALIZA LA PLANILLA
    public void actualizarTablaPlanilla(ArrayList<cEmpleado> planilla) {

        modeloPlanilla.setRowCount(0);
        for (int i = 0; i < planilla.size(); i++) {
            modeloPlanilla.addRow(new Object[]{planilla.get(i).getId(), planilla.get(i).getPlanilla(), planilla.get(i).getMesPlanilla(), planilla.get(i).getAnioPlanilla(), "₡ " + objDF.format(planillasImpresas.get(i).getSalarioNetoPlanilla())});
        }

    }
   // VERIFICA SI ES UN ENTERO 
    public void verificarEntero(String id) {
        int n = 0;

        try {
            n = Integer.parseInt(id);
            reporteId(n);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "HA INGRESADO UNA:  " + " INCORRECTA; POR FAVOR INGRESE NUMEROS PARA ESTE CAMPO ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }
//REALIZA EL PRIMER REPORTE
    public void reporteId(int id) {
        double salario = 0;

        for (int i = 0; i < planillasImpresas.size(); i++) {
            if (planillasImpresas.get(i).getId() == id) {
                texto += planillasImpresas.get(i).getId() + "  " + planillasImpresas.get(i).getPlanilla() + "  " + planillasImpresas.get(i).getMesPlanilla() + "  " + planillasImpresas.get(i).getAnioPlanilla() + " " +"₡ " + objDF.format(planillasImpresas.get(i).getSalarioNetoPlanilla()) + "\n";
                salario += planillasImpresas.get(i).getSalarioNetoPlanilla();
            }
        }
        texto += "\n" + "___________________________________________" + "\n" + "SUMA TOTAL SALARIO: " + "₡ " + objDF.format(salario);

    }
//REALIZA EL SEGUNDO REPORTE
    public void reportePlanilla(String planilla) {
        double salario = 0;
        for (int i = 0; i < planillasImpresas.size(); i++) {
            if (planillasImpresas.get(i).getPlanilla().equalsIgnoreCase(planilla)) {
                texto += planillasImpresas.get(i).getId() + "  " + planillasImpresas.get(i).getPlanilla() + "  " + planillasImpresas.get(i).getMesPlanilla() + "  " + planillasImpresas.get(i).getAnioPlanilla() + " " +"₡ " + objDF.format(planillasImpresas.get(i).getSalarioNetoPlanilla())  + "\n";
                salario += planillasImpresas.get(i).getSalarioNetoPlanilla();
            }
        }
        texto += "\n" + "___________________________________________" + "\n" + "SUMA TOTAL SALARIO: " + "₡ " + objDF.format(salario);

    }
//ATRIBUTOS
    private Reporte reporte;
    private String texto = "";
    private Color azulOscuro = new Color(39, 76, 119);
    private Color gris = new Color(139, 140, 137);
    String patron = "###,###.##";
    DecimalFormat objDF = new DecimalFormat(patron);
    static ArrayList<cEmpleado> planillasImpresas = new ArrayList<cEmpleado>();
    private DefaultTableModel modeloPlanilla;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarReporte1;
    private javax.swing.JButton generarReporte2;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opcionPlanilla;
    private javax.swing.JTable tablaPlanilla;
    // End of variables declaration//GEN-END:variables
}
