/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
  import java.awt.Image;

  import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte1
     */
    public Reporte(String texto) {
       initComponents();

       this.texto=texto;
       ImageIcon icono = new ImageIcon("src/assets/iconoJFrame.png");
       this.setIconImage(icono.getImage());
       llenarTextArea();
    
   
        
    }
    





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        generarReporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reporteBrindado = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTES");
        setBackground(new java.awt.Color(231, 236, 239));
        setIconImages(null);

        generarReporte.setBackground(new java.awt.Color(39, 76, 119));
        generarReporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        generarReporte.setForeground(new java.awt.Color(231, 236, 239));
        generarReporte.setText("Guardar Reporte");
        generarReporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generarReporte.setBorderPainted(false);
        generarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardar(evt);
            }
        });

        reporteBrindado.setEditable(false);
        reporteBrindado.setColumns(20);
        reporteBrindado.setRows(5);
        jScrollPane2.setViewportView(reporteBrindado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(generarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generarReporte)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar
       guardarComo();
    }//GEN-LAST:event_guardar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte("").setVisible(true);
            }
        });
    }
    
    // METODOS 
    // LLENA EL TEXTAREA CON EL TEXTO
    public void llenarTextArea(){
        
     reporteBrindado.setForeground(new Color(39,76,119));
        
        reporteBrindado.setText(texto);
        
    }
    // METODO PARA GUARDAR COMO 
        public void guardarComo(){
        JFileChooser guardar= new JFileChooser();
        guardar.showSaveDialog(null);
         guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        File archivo = guardar.getSelectedFile();
        if (archivo != null) { 
        guardarFichero(reporteBrindado.getText(),archivo);
    } else{
          JOptionPane.showMessageDialog(this, "EL ARCHIVO NO SE HA GUARDADO","INFORMACION", JOptionPane.INFORMATION_MESSAGE);  
        }
        
        
    }
        // ESCRIBE EL ARCHIVO
        
        public void guardarFichero(String cadena, File archivo){

    FileWriter escribir;
    try {

        escribir = new FileWriter(archivo, true);
        escribir.write(cadena);
        escribir.close();

    } catch (FileNotFoundException ex) {
        JOptionPane.showMessageDialog(null, "EROROR AL GUARDAR, ESCRIBA EL NOMBRE SEGUIDO DE LA EXTENSION PUEDE USAR .txt, .doc","ERROR", JOptionPane.ERROR_MESSAGE);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error al guardar, en la salida","ERROR", JOptionPane.ERROR_MESSAGE);
    } 
}
      
 private String texto;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea reporteBrindado;
    // End of variables declaration//GEN-END:variables
}
