/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import static Interface.Planilla.planillasImpresas;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Usuario() {
        initComponents();

        ListaEmpleados = empleados.getArrayList();
        formatoTabla();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        textoID = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        puesto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuarios = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        textoID1 = new javax.swing.JLabel();
        idBusqueda = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(231, 236, 239));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(750, 461));
        setMinimumSize(new java.awt.Dimension(750, 461));
        setPreferredSize(new java.awt.Dimension(750, 461));

        textoID.setBackground(new java.awt.Color(39, 76, 119));
        textoID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoID.setForeground(new java.awt.Color(39, 76, 119));
        textoID.setText("ID");

        id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        id.setForeground(new java.awt.Color(139, 140, 137));
        id.setText("Ingrese la ID");
        id.setMaximumSize(new java.awt.Dimension(85, 22));
        id.setMinimumSize(new java.awt.Dimension(85, 22));
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarId(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(39, 76, 119));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 76, 119));
        jLabel2.setText("Nombre");

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(139, 140, 137));
        nombre.setText("Ingrese el nombre ");
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarNombre(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(39, 76, 119));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 76, 119));
        jLabel3.setText("Apellido");

        apellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apellido.setForeground(new java.awt.Color(139, 140, 137));
        apellido.setText("Ingrese el apellido");
        apellido.setMinimumSize(new java.awt.Dimension(64, 25));
        apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarApellido(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(39, 76, 119));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 76, 119));
        jLabel4.setText("Edad");

        edad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edad.setForeground(new java.awt.Color(139, 140, 137));
        edad.setText("Ingrese la edad");
        edad.setMaximumSize(new java.awt.Dimension(116, 22));
        edad.setMinimumSize(new java.awt.Dimension(116, 22));
        edad.setPreferredSize(new java.awt.Dimension(116, 22));
        edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarEdad(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(39, 76, 119));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 76, 119));
        jLabel5.setText("Puesto");

        puesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        puesto.setForeground(new java.awt.Color(139, 140, 137));
        puesto.setText("Ingrese el puesto ");
        puesto.setMaximumSize(new java.awt.Dimension(116, 22));
        puesto.setMinimumSize(new java.awt.Dimension(116, 22));
        puesto.setPreferredSize(new java.awt.Dimension(116, 22));
        puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarPuesto(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(39, 76, 119));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 76, 119));
        jLabel6.setText("Fecha ingreso");

        jButton1.setBackground(new java.awt.Color(39, 76, 119));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(231, 236, 239));
        jButton1.setText("Ingresar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarUsuarios(evt);
            }
        });

        usuarios.setBackground(new java.awt.Color(231, 236, 239));
        usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarios.setGridColor(new java.awt.Color(39, 76, 119));
        usuarios.setShowGrid(true);
        usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usuarios);

        jButton2.setBackground(new java.awt.Color(39, 76, 119));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(231, 236, 239));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificar(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(39, 76, 119));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(231, 236, 239));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/borrar.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borrarUsuario(evt);
            }
        });

        textoID1.setBackground(new java.awt.Color(39, 76, 119));
        textoID1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoID1.setForeground(new java.awt.Color(39, 76, 119));
        textoID1.setText("ID");

        idBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idBusqueda.setForeground(new java.awt.Color(139, 140, 137));
        idBusqueda.setText("Ingrese la ID");
        idBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarId(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(39, 76, 119));
        buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscar.setForeground(new java.awt.Color(231, 236, 239));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buscar.png"))); // NOI18N
        buscar.setText("Buscar");
        buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscar.setBorderPainted(false);
        buscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fecha.setForeground(new java.awt.Color(139, 140, 137));
        fecha.setText("Ingrese la fecha");
        fecha.setMaximumSize(new java.awt.Dimension(116, 22));
        fecha.setMinimumSize(new java.awt.Dimension(116, 22));
        fecha.setPreferredSize(new java.awt.Dimension(116, 22));
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaIngresarPuesto(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(39, 76, 119));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(231, 236, 239));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/limpiar.png"))); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setBorderPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoID1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoID)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(buscar)
                    .addComponent(idBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void ingresarUsuarios(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarUsuarios

        String nombre, apellido, puesto, id, edad, fecha;
        boolean verificacionIdExistente = true;

        id = this.id.getText();
        edad = this.edad.getText();
        nombre = this.nombre.getText();
        apellido = this.apellido.getText();
        puesto = this.puesto.getText();
        fecha = this.fecha.getText();
        fecha = validacionFecha(fecha);
        int idIngresado = verificarEntero(id, "ID");
        int edadIngresada = verificarEntero(edad, "EDAD");
        
        if(this.id.isEnabled()){
            boolean idRepitido = verificacionIdExistente = verificacionIdNoRepetido(idIngresado);
            if (idIngresado > 0 && edadIngresada >= 18 && !nombre.equals("") && !apellido.equals("") && !puesto.equals("") && !verificacionIdExistente && !fecha.equals("") && idRepitido == false) {

            empleados.IngresaUsuarios(idIngresado, nombre, apellido, edadIngresada, puesto, fecha);
            llenarTabla();

        } else {
            JOptionPane.showMessageDialog(this, "VERIFIQUE LOS DATOS QUE DESEA INGRESAR ALGUNO DE LOS DATOS NO CUMPLE CON EL REQUERIMIENTO DESEADO ", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 
        }
        else{
             JOptionPane.showMessageDialog(this, "POR FAVOR MODIFIQUE ESTE USUARIO O ELIMINELO ANTES DE INGRESAR UNO NUEVO O PRESIONES DOS VECES CLICK PARA CANCELAR", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }

       


    }//GEN-LAST:event_ingresarUsuarios

    private void ingresarId(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarId
        if (id.isEnabled()) {
            id.setText("");
            id.setForeground(azulOscuro);
        }
        else{
            contador++;
        }
        if(contador==2&& !this.id.isEnabled()){
            this.id.setEnabled(true);
            this.id.setEditable(true);
            contador=0;
        }

    }//GEN-LAST:event_ingresarId

    private void ingresarNombre(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarNombre
        nombre.setText("");
        nombre.setForeground(azulOscuro);
    }//GEN-LAST:event_ingresarNombre

    private void ingresarApellido(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarApellido
        apellido.setText("");
        apellido.setForeground(azulOscuro);
    }//GEN-LAST:event_ingresarApellido

    private void IngresarEdad(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarEdad
        edad.setText("");
        edad.setForeground(azulOscuro);
    }//GEN-LAST:event_IngresarEdad

    private void IngresarPuesto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarPuesto
        puesto.setText("");
        puesto.setForeground(azulOscuro);
    }//GEN-LAST:event_IngresarPuesto

    private void usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosMouseClicked
        DefaultTableModel modelo2 = modelo;

        String id = modelo2.getValueAt(usuarios.getSelectedRow(), 0).toString();
        String nombre = modelo2.getValueAt(usuarios.getSelectedRow(), 1).toString();
        String apellido = modelo2.getValueAt(usuarios.getSelectedRow(), 2).toString();
        String edad = modelo2.getValueAt(usuarios.getSelectedRow(), 3).toString();
        String puesto = modelo2.getValueAt(usuarios.getSelectedRow(), 4).toString();
        String fecha = modelo2.getValueAt(usuarios.getSelectedRow(), 5).toString();
        registrado = registradoEnPLanilla(id);
   
        if (!registrado) {
            this.id.setText(id);
            this.idAntiguo = Integer.parseInt(id);
            this.nombre.setText(nombre);
            this.apellido.setText(apellido);
            this.edad.setText(edad);
            this.puesto.setText(puesto);
            this.fecha.setText(fecha);
            this.id.setEnabled(true);
            this.id.setEditable(true);
            this.id.setForeground(azulOscuro);
            this.nombre.setForeground(azulOscuro);
            this.apellido.setForeground(azulOscuro);
            this.edad.setForeground(azulOscuro);
            this.puesto.setForeground(azulOscuro);
            this.fecha.setForeground(azulOscuro);
        } else {
            this.idAntiguo = Integer.parseInt(id);
            this.id.setEditable(false);
            JOptionPane.showMessageDialog(this, "EL USUARIO YA HA SIDO INGRESADO EN PLANILLA POR ESTA RAZON EL ID NO PUEDE SER MODIFICADO ", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            this.id.setText(id);
            this.nombre.setText(nombre);
            this.apellido.setText(apellido);
            this.edad.setText(edad);
            this.puesto.setText(puesto);
            this.fecha.setText(fecha);
            this.id.setEnabled(false);
            this.id.setForeground(azulOscuro);
            this.nombre.setForeground(azulOscuro);
            this.apellido.setForeground(azulOscuro);
            this.edad.setForeground(azulOscuro);
            this.puesto.setForeground(azulOscuro);
            this.fecha.setForeground(azulOscuro);
        }
        System.out.print(this.idAntiguo);


    }//GEN-LAST:event_usuariosMouseClicked

    private void fechaIngresarPuesto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaIngresarPuesto
        fecha.setText("");
        fecha.setForeground(azulOscuro);
    }//GEN-LAST:event_fechaIngresarPuesto

    private void modificar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar
       // MIDIFICA EL ARCHVIO
        
        String nombre, apellido, puesto, id, edad, fecha;

        id = this.id.getText();
        edad = this.edad.getText();
        nombre = this.nombre.getText();
        apellido = this.apellido.getText();
        puesto = this.puesto.getText();
        fecha = this.fecha.getText();
        fecha = validacionFecha(fecha);
        
        int idIngresado = verificarEntero(id, "ID");
        int edadIngresada = verificarEntero(edad, "EDAD");
        if (idIngresado > 0 && edadIngresada >= 18 && !nombre.equals("") && !apellido.equals("") && !puesto.equals("") && !fecha.equals("")) {
            ListaEmpleados = empleados.modificarArrayList(idAntiguo, idIngresado, nombre, apellido, edadIngresada, puesto, fecha, registrado);
            empleados.escribirArchivo(ListaEmpleados);
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "VERIFIQUE LOS DATOS QUE DESEA MODIFICAR; ALGUNO DE LOS DATOS NO CUMPLE CON EL REQUERIMIENTO DESEADO ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        this.id.setEnabled(true);
        this.id.setEditable(true);
    }//GEN-LAST:event_modificar

    private void borrarUsuario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarUsuario
       // BORRA EL USUARIO
        if (!registradoEnPLanilla(this.id.getText())) {
            int id = Integer.parseInt(this.id.getText());
            ListaEmpleados = empleados.borrarArrayList(id);
            empleados.escribirArchivo(ListaEmpleados);
            llenarTabla();
            this.id.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "NO SE PUEDE ELIMINAR PORQUE YA SE ENCUENTRA EN PLANILLA ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_borrarUsuario

    private void buscarId(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarId
        // BUSCA EL ID 
        this.idBusqueda.setText("");
        this.idBusqueda.setForeground(azulOscuro);
        this.id.setText("Ingrese la ID");
        this.nombre.setText("Ingrese el nombre");
        this.apellido.setText("Ingrese el apellido");
        this.edad.setText("Ingrese la edad");
        this.puesto.setText("Ingrese el puesto");
        this.fecha.setText("Ingrese la fecha");
        this.id.setForeground(gris);
        this.nombre.setForeground(gris);
        this.apellido.setForeground(gris);
        this.edad.setForeground(gris);
        this.puesto.setForeground(gris);
        this.fecha.setForeground(gris);
    }//GEN-LAST:event_buscarId

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        int indice = 0;
        int idIngresado = verificarEntero(this.idBusqueda.getText(), "ID");
        for (int i = 0; i < ListaEmpleados.size(); i++) {
            if (ListaEmpleados.get(i).getId() == idIngresado) {
                DefaultTableModel modelo2 = modelo;
                this.id.setText(modelo2.getValueAt(indice, 0).toString());
                this.nombre.setText(modelo2.getValueAt(indice, 1).toString());
                this.apellido.setText(modelo2.getValueAt(indice, 2).toString());
                this.edad.setText(modelo2.getValueAt(indice, 3).toString());
                this.puesto.setText(modelo2.getValueAt(indice, 4).toString());
                this.fecha.setText(modelo2.getValueAt(indice, 5).toString());
                this.id.setForeground(azulOscuro);
                this.nombre.setForeground(azulOscuro);
                this.apellido.setForeground(azulOscuro);
                this.edad.setForeground(azulOscuro);
                this.puesto.setForeground(azulOscuro);
                this.fecha.setForeground(azulOscuro);
                break;
            }
            else{
               JOptionPane.showMessageDialog(this, "ID NO ENCONTRADO ", "ERROR", JOptionPane.ERROR_MESSAGE); 
               this.idBusqueda.setText("Ingrese la ID");
            }
        }

    }//GEN-LAST:event_buscarMousePressed

    private void limpiar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiar
        this.id.setText("");
        this.nombre.setText("");
        this.apellido.setText("");
        this.edad.setText("");
        this.puesto.setText("");
        this.fecha.setText("");
        
    }//GEN-LAST:event_limpiar

    /**
     * ******************************************************************************************
     */
//METODOS
    // DA FORMATO A LA TABLA 
    public void formatoTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.addColumn("id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Edad");
        modelo.addColumn("Puesto");
        modelo.addColumn("Fecha");
        this.usuarios.setModel(modelo);
    }
//LLENA LA TABLA CON EL ARRAYLSIT

    public void llenarTabla() {
        modelo.setRowCount(0);
        for (int i = 0; i < ListaEmpleados.size(); i++) {
            modelo.addRow(new Object[]{ListaEmpleados.get(i).getId(), ListaEmpleados.get(i).getNombre(), ListaEmpleados.get(i).getApellido(), ListaEmpleados.get(i).getEdad(), ListaEmpleados.get(i).getPuesto(), ListaEmpleados.get(i).getFecha()});
        }
    }

    // METODO QUE VALIDA LA FECHA
    public String validacionFecha(String fecha) {
        String fechaIngresada = "";
        try {
            String[] componentes = fecha.split("/");
            int dia = Integer.parseInt(componentes[0]);
            int mes = Integer.parseInt(componentes[1]);
            int anio = Integer.parseInt(componentes[2]);

            if (dia < 1 || dia > 31 || mes < 1 || mes > 12 || anio < 1000 || anio > 9999) {
                JOptionPane.showMessageDialog(nombre, "HA INGRESADO UNA FECHA INCORRECTA POR FAVOR VERIFIQUE LO QUE ESCRIBIO  ", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {

                fechaIngresada = String.format("%02d/%02d/%04d", dia, mes, anio);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(nombre, "HA INGRESADO UNA FECHA INCORRECTA POR FAVOR ESCRIBA DE NUEVO LA FECHA CON EL SIGUIENTE FORMATO D/M/A", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(nombre, "HA INGRESADO UNA FECHA INCORRECTA POR FAVOR ESCRIBA DE NUEVO LA FECHA CON EL SIGUIENTE FORMATO D/M/A", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return fechaIngresada;
    }
//VERIFICA ENTERO
    public int verificarEntero(String s, String mensaje) {
        int n = 0;

        try {
            n = Integer.parseInt(s);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(nombre, "HA INGRESADO UNA:  " + mensaje + " INCORRECTA; POR FAVOR INGRESE NUMEROS PARA ESTE CAMPO " + mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return n;

    }


    //VERIFICA SI EL ID EXISTE 
    public boolean verificacionIdNoRepetido(int id) {

        boolean existe = false;
        for (int i = 0; i < ListaEmpleados.size(); i++) {
            if (ListaEmpleados.get(i).getId() == id) {

                JOptionPane.showMessageDialog(this, "EL ID YA HA SIDO INGRESADO POR FAVOR INSERTE OTRO ", "ERROR", JOptionPane.ERROR_MESSAGE);
                existe = true;
                break;

            } else {

                existe = false;
            }
        }
        return existe;
    }
//VERIFICA  SI EL USUARIO FUE ASIGNADO A PLANILLA PARA NO ELIMINARLO O MODIFICAR EL ID
    public boolean registradoEnPLanilla(String id) {
        boolean registrado = false;
        for (int i = 0; i < planillasImpresas.size(); i++) {
            if (Integer.parseInt(id) == planillasImpresas.get(i).getId()) {
                registrado = true;
            } else {
                registrado = false;
            }
        }
        return registrado;
    }


    /**
     * *******************************************************************
     */
    // atributos 
    private Color azulOscuro = new Color(39, 76, 119);
    private Color gris = new Color(139, 140, 137);
    ArrayList<cEmpleado> ListaEmpleados = new ArrayList<cEmpleado>();
    private DefaultTableModel modelo = new DefaultTableModel();
    cEmpleado empleados = new cEmpleado();
    private int idAntiguo;
    private boolean registrado;
    private int contador=0;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField puesto;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoID1;
    private javax.swing.JTable usuarios;
    // End of variables declaration//GEN-END:variables

}
